# Data cleanup

Since the raw data has a lot of unneccesary data, I first had to filter all of them out and change existing features in order to produce the best results.

In [1]:
import requests
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Raw housing data.csv")

In [3]:
df.head()

,web-scraper-order,web-scraper-start-url,Address,Address-href,Price,Bedrooms,Bathrooms,Parkings,Type,Size,Levels,Garage,Average household income,Total population
0,1673723039-48,https://www.zoocasa.com/toronto-on-real-estate...,803 - 63 St Clair Ave W,https://www.zoocasa.com/toronto-on-real-estate...,1540180.0,2.0,2.0,1.0,Condo Apt,1200–1399 sqft,Apartment,Undergrnd,122917.0,14768.0
1,1673723073-49,https://www.zoocasa.com/toronto-on-real-estate...,2305 - 33 Singer Crt,https://www.zoocasa.com/toronto-on-real-estate...,896000.0,2.0,2.0,1.0,Condo Apt,900–999 sqft,Apartment,Undergrnd,62171.0,4089.0
2,1673723085-50,https://www.zoocasa.com/toronto-on-real-estate...,912 - 38 Elm St,https://www.zoocasa.com/toronto-on-real-estate...,705600.0,1.0,1.0,1.0,Condo Apt,700–799 sqft,Apartment,Undergrnd,76677.0,37644.0
3,1673723097-51,https://www.zoocasa.com/toronto-on-real-estate...,3 - 2512 Bloor St W,https://www.zoocasa.com/toronto-on-real-estate...,801000.0,2.0,1.0,1.0,Condo Apt,800–899 sqft,Apartment,Attached,168492.0,5488.0
4,1673723109-52,https://www.zoocasa.com/toronto-on-real-estate...,461 Woburn Ave,https://www.zoocasa.com/toronto-on-real-estate...,2355000.0,3.0,4.0,3.0,Detached,N/A sqft,2-Storey,None,187227.0,6526.0

In [4]:
df.describe()

,Price,Bedrooms,Bathrooms,Parkings,Average household income,Total population
count,1.955500e+04,19554.000000,19554.000000,19554.000000,17331.000000,17331.000000
mean,1.056248e+06,2.274880,2.075023,1.869822,86552.293578,16019.689631
std,8.625209e+05,1.134163,1.125504,8.306068,52992.904751,15707.821335
min,1.500000e+02,0.000000,0.000000,0.000000,30907.000000,378.000000
25%,6.300000e+05,1.000000,1.000000,1.000000,62171.000000,5879.000000
50%,8.600000e+05,2.000000,2.000000,1.000000,72747.000000,9621.000000
75%,1.280000e+06,3.000000,2.000000,2.000000,86711.000000,20810.000000
max,1.719800e+07,9.000000,16.000000,1111.000000,622238.000000,73552.000000

In [5]:
df_copy = df

In [6]:
df_copy.head()

,web-scraper-order,web-scraper-start-url,Address,Address-href,Price,Bedrooms,Bathrooms,Parkings,Type,Size,Levels,Garage,Average household income,Total population
0,1673723039-48,https://www.zoocasa.com/toronto-on-real-estate...,803 - 63 St Clair Ave W,https://www.zoocasa.com/toronto-on-real-estate...,1540180.0,2.0,2.0,1.0,Condo Apt,1200–1399 sqft,Apartment,Undergrnd,122917.0,14768.0
1,1673723073-49,https://www.zoocasa.com/toronto-on-real-estate...,2305 - 33 Singer Crt,https://www.zoocasa.com/toronto-on-real-estate...,896000.0,2.0,2.0,1.0,Condo Apt,900–999 sqft,Apartment,Undergrnd,62171.0,4089.0
2,1673723085-50,https://www.zoocasa.com/toronto-on-real-estate...,912 - 38 Elm St,https://www.zoocasa.com/toronto-on-real-estate...,705600.0,1.0,1.0,1.0,Condo Apt,700–799 sqft,Apartment,Undergrnd,76677.0,37644.0
3,1673723097-51,https://www.zoocasa.com/toronto-on-real-estate...,3 - 2512 Bloor St W,https://www.zoocasa.com/toronto-on-real-estate...,801000.0,2.0,1.0,1.0,Condo Apt,800–899 sqft,Apartment,Attached,168492.0,5488.0
4,1673723109-52,https://www.zoocasa.com/toronto-on-real-estate...,461 Woburn Ave,https://www.zoocasa.com/toronto-on-real-estate...,2355000.0,3.0,4.0,3.0,Detached,N/A sqft,2-Storey,None,187227.0,6526.0

In [7]:
df_copy = df_copy.drop(["web-scraper-order", 'web-scraper-start-url', 'Address-href'], axis=1)

# Modifying the Size column
Since I required all the data to be numerical for data processing, I had to modify the size column and also remove any null data. My first step was to remove the sqft at the end of every size value, this was done with the following code:

In [8]:
def remove_sqft(size):
    edited = size[0:(len(size) - 5)]
    return edited

df_copy['Size'] = df_copy.apply(lambda x: remove_sqft(x.Size), axis=1)

In [9]:
df_copy

,Address,Price,Bedrooms,Bathrooms,Parkings,Type,Size,Levels,Garage,Average household income,Total population
0,803 - 63 St Clair Ave W,1540180.0,2.0,2.0,1.0,Condo Apt,1200–1399,Apartment,Undergrnd,122917.0,14768.0
1,2305 - 33 Singer Crt,896000.0,2.0,2.0,1.0,Condo Apt,900–999,Apartment,Undergrnd,62171.0,4089.0
2,912 - 38 Elm St,705600.0,1.0,1.0,1.0,Condo Apt,700–799,Apartment,Undergrnd,76677.0,37644.0
3,3 - 2512 Bloor St W,801000.0,2.0,1.0,1.0,Condo Apt,800–899,Apartment,Attached,168492.0,5488.0
4,461 Woburn Ave,2355000.0,3.0,4.0,3.0,Detached,N/A,2-Storey,None,187227.0,6526.0
...,...,...,...,...,...,...,...,...,...,...,...
19552,515 - 69 Lynn Williams St,575000.0,1.0,1.0,0.0,Condo Apt,700–799,Apartment,Undergrnd,81702.0,6801.0
19553,808 - 1600 Keele St,430000.0,1.0,1.0,1.0,Condo Apt,500–599,Apartment,Undergrnd,57144.0,17602.0
19554,1811 - 195 Redpath Ave,580000.0,1.0,2.0,0.0,Condo Apt,500–599,Apartment,None,85636.0,23133.0
19555,487 Brookdale Ave,3425000.0,4.0,5.0,6.0,Detached,N/A,2-Storey,Built-In,187227.0,6526.0
19556,2316 - 30 Shore Breeze Dr,900000.0,2.0,2.0,1.0,Condo Apt,800–899,Apartment,Undergrnd,117457.0,4322.0

In [10]:
df_copy = df_copy.dropna()

In [11]:
df_copy

,Address,Price,Bedrooms,Bathrooms,Parkings,Type,Size,Levels,Garage,Average household income,Total population
0,803 - 63 St Clair Ave W,1540180.0,2.0,2.0,1.0,Condo Apt,1200–1399,Apartment,Undergrnd,122917.0,14768.0
1,2305 - 33 Singer Crt,896000.0,2.0,2.0,1.0,Condo Apt,900–999,Apartment,Undergrnd,62171.0,4089.0
2,912 - 38 Elm St,705600.0,1.0,1.0,1.0,Condo Apt,700–799,Apartment,Undergrnd,76677.0,37644.0
3,3 - 2512 Bloor St W,801000.0,2.0,1.0,1.0,Condo Apt,800–899,Apartment,Attached,168492.0,5488.0
4,461 Woburn Ave,2355000.0,3.0,4.0,3.0,Detached,N/A,2-Storey,None,187227.0,6526.0
...,...,...,...,...,...,...,...,...,...,...,...
19552,515 - 69 Lynn Williams St,575000.0,1.0,1.0,0.0,Condo Apt,700–799,Apartment,Undergrnd,81702.0,6801.0
19553,808 - 1600 Keele St,430000.0,1.0,1.0,1.0,Condo Apt,500–599,Apartment,Undergrnd,57144.0,17602.0
19554,1811 - 195 Redpath Ave,580000.0,1.0,2.0,0.0,Condo Apt,500–599,Apartment,None,85636.0,23133.0
19555,487 Brookdale Ave,3425000.0,4.0,5.0,6.0,Detached,N/A,2-Storey,Built-In,187227.0,6526.0
19556,2316 - 30 Shore Breeze Dr,900000.0,2.0,2.0,1.0,Condo Apt,800–899,Apartment,Undergrnd,117457.0,4322.0

The next step was to convert the range of the value to a single numerical integer. I considered the best way to go about this was to take the average of the range as this would give the best possible estimate of the size and remane the name of the column to "Estimated Size/ft" to keep the data set accurate. It was done through the following code:

In [12]:
def get_avg_size(size):
    if (size) == 'N/A':
        return size
    elif "-" in str(size):
        numbers = size.split("-")
        result = (int(numbers[0]) + int(numbers[1])) / 2
        return result
    elif '–' in str(size):
        numbers1 = size.split('–')
        result1 = (int(numbers1[0]) + int(numbers1[1])) / 2
        return result1
    else:
        return size

In [13]:
df['Size'].dtype

dtype('O')

In [14]:
 pd.options.mode.chained_assignment = None

In [15]:
df_copy['Size'] = df_copy.apply(lambda x: get_avg_size(x.Size), axis=1)

In [16]:
df_copy

,Address,Price,Bedrooms,Bathrooms,Parkings,Type,Size,Levels,Garage,Average household income,Total population
0,803 - 63 St Clair Ave W,1540180.0,2.0,2.0,1.0,Condo Apt,1299.5,Apartment,Undergrnd,122917.0,14768.0
1,2305 - 33 Singer Crt,896000.0,2.0,2.0,1.0,Condo Apt,949.5,Apartment,Undergrnd,62171.0,4089.0
2,912 - 38 Elm St,705600.0,1.0,1.0,1.0,Condo Apt,749.5,Apartment,Undergrnd,76677.0,37644.0
3,3 - 2512 Bloor St W,801000.0,2.0,1.0,1.0,Condo Apt,849.5,Apartment,Attached,168492.0,5488.0
4,461 Woburn Ave,2355000.0,3.0,4.0,3.0,Detached,N/A,2-Storey,None,187227.0,6526.0
...,...,...,...,...,...,...,...,...,...,...,...
19552,515 - 69 Lynn Williams St,575000.0,1.0,1.0,0.0,Condo Apt,749.5,Apartment,Undergrnd,81702.0,6801.0
19553,808 - 1600 Keele St,430000.0,1.0,1.0,1.0,Condo Apt,549.5,Apartment,Undergrnd,57144.0,17602.0
19554,1811 - 195 Redpath Ave,580000.0,1.0,2.0,0.0,Condo Apt,549.5,Apartment,None,85636.0,23133.0
19555,487 Brookdale Ave,3425000.0,4.0,5.0,6.0,Detached,N/A,2-Storey,Built-In,187227.0,6526.0
19556,2316 - 30 Shore Breeze Dr,900000.0,2.0,2.0,1.0,Condo Apt,849.5,Apartment,Undergrnd,117457.0,4322.0

In [17]:
df_copy = df_copy.rename(columns = {'Size' : 'Estimated Size/ft'})

In [18]:
df_copy

,Address,Price,Bedrooms,Bathrooms,Parkings,Type,Estimated Size/ft,Levels,Garage,Average household income,Total population
0,803 - 63 St Clair Ave W,1540180.0,2.0,2.0,1.0,Condo Apt,1299.5,Apartment,Undergrnd,122917.0,14768.0
1,2305 - 33 Singer Crt,896000.0,2.0,2.0,1.0,Condo Apt,949.5,Apartment,Undergrnd,62171.0,4089.0
2,912 - 38 Elm St,705600.0,1.0,1.0,1.0,Condo Apt,749.5,Apartment,Undergrnd,76677.0,37644.0
3,3 - 2512 Bloor St W,801000.0,2.0,1.0,1.0,Condo Apt,849.5,Apartment,Attached,168492.0,5488.0
4,461 Woburn Ave,2355000.0,3.0,4.0,3.0,Detached,N/A,2-Storey,None,187227.0,6526.0
...,...,...,...,...,...,...,...,...,...,...,...
19552,515 - 69 Lynn Williams St,575000.0,1.0,1.0,0.0,Condo Apt,749.5,Apartment,Undergrnd,81702.0,6801.0
19553,808 - 1600 Keele St,430000.0,1.0,1.0,1.0,Condo Apt,549.5,Apartment,Undergrnd,57144.0,17602.0
19554,1811 - 195 Redpath Ave,580000.0,1.0,2.0,0.0,Condo Apt,549.5,Apartment,None,85636.0,23133.0
19555,487 Brookdale Ave,3425000.0,4.0,5.0,6.0,Detached,N/A,2-Storey,Built-In,187227.0,6526.0
19556,2316 - 30 Shore Breeze Dr,900000.0,2.0,2.0,1.0,Condo Apt,849.5,Apartment,Undergrnd,117457.0,4322.0

# Enrichening the data
Using Google's Geocoding API, I was able to further enhance the data set by using the addresses and changing them into their respective latitude and longitude co-ordinates. This was done as sometimes there's a link between the geographical data of a location and the targeted data. It was done through the following code:

In [19]:
# This block is now commented out so that the google api is not unnecessarily called.

# GOOGLE_API_KEY = 'my key was used here' 

# def extract_lat_long_via_address(address_or_zipcode):
#    lat, lng = None, None
#    api_key = GOOGLE_API_KEY
#    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
#    endpoint = f"{base_url}?address={address_or_zipcode}&key={api_key}"
#    r = requests.get(endpoint)
#    if r.status_code not in range(200, 299):
#        return None, None
#    try:
#        results = r.json()['results'][0]
#        lat = results['geometry']['location']['lat']
#        lng = results['geometry']['location']['lng']
#    except:
#        pass
#    return lat, lng

#def enrich_with_geocoding_api(row):
#    column_name = 'Address'
#    address_value = row[column_name]
#    address_lat, address_lng = extract_lat_long_via_address(address_value)
#    row['lat'] = address_lat
#    row['lng'] = address_lng
#    return row

#df_copy = df_copy.apply(enrich_with_geocoding_api, axis=1)

# Now we will only work with the "edited housing data.csv"

In [20]:
df_copy

,Address,Price,Bedrooms,Bathrooms,Parkings,Type,Estimated Size/ft,Levels,Garage,Average household income,Total population,lat,lng
0,803 - 63 St Clair Ave W,1540180.0,2.0,2.0,1.0,Condo Apt,1299.5,Apartment,Undergrnd,122917.0,14768.0,43.680467,-79.430436
1,2305 - 33 Singer Crt,896000.0,2.0,2.0,1.0,Condo Apt,949.5,Apartment,Undergrnd,62171.0,4089.0,43.769796,-79.369430
2,912 - 38 Elm St,705600.0,1.0,1.0,1.0,Condo Apt,749.5,Apartment,Undergrnd,76677.0,37644.0,43.657599,-79.383640
3,3 - 2512 Bloor St W,801000.0,2.0,1.0,1.0,Condo Apt,849.5,Apartment,Attached,168492.0,5488.0,43.640357,-79.542820
4,461 Woburn Ave,2355000.0,3.0,4.0,3.0,Detached,N/A,2-Storey,None,187227.0,6526.0,43.724902,-79.418350
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19552,515 - 69 Lynn Williams St,575000.0,1.0,1.0,0.0,Condo Apt,749.5,Apartment,Undergrnd,81702.0,6801.0,43.639029,-79.415923
19553,808 - 1600 Keele St,430000.0,1.0,1.0,1.0,Condo Apt,549.5,Apartment,Undergrnd,57144.0,17602.0,43.679358,-79.470675
19554,1811 - 195 Redpath Ave,580000.0,1.0,2.0,0.0,Condo Apt,549.5,Apartment,None,85636.0,23133.0,43.707888,-79.392802
19555,487 Brookdale Ave,3425000.0,4.0,5.0,6.0,Detached,N/A,2-Storey,Built-In,187227.0,6526.0,NaN,NaN
19556,2316 - 30 Shore Breeze Dr,900000.0,2.0,2.0,1.0,Condo Apt,849.5,Apartment,Undergrnd,117457.0,4322.0,43.623764,-79.479165

In [21]:
df_copy = df_copy.dropna()

In [22]:
df_copy

,Address,Price,Bedrooms,Bathrooms,Parkings,Type,Estimated Size/ft,Levels,Garage,Average household income,Total population,lat,lng
0,803 - 63 St Clair Ave W,1540180.0,2.0,2.0,1.0,Condo Apt,1299.5,Apartment,Undergrnd,122917.0,14768.0,43.680467,-79.430436
1,2305 - 33 Singer Crt,896000.0,2.0,2.0,1.0,Condo Apt,949.5,Apartment,Undergrnd,62171.0,4089.0,43.769796,-79.369430
2,912 - 38 Elm St,705600.0,1.0,1.0,1.0,Condo Apt,749.5,Apartment,Undergrnd,76677.0,37644.0,43.657599,-79.383640
3,3 - 2512 Bloor St W,801000.0,2.0,1.0,1.0,Condo Apt,849.5,Apartment,Attached,168492.0,5488.0,43.640357,-79.542820
4,461 Woburn Ave,2355000.0,3.0,4.0,3.0,Detached,N/A,2-Storey,None,187227.0,6526.0,43.724902,-79.418350
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19551,1106 - 63 St Clair Ave W,1300000.0,2.0,2.0,1.0,Condo Apt,1299.5,Apartment,Undergrnd,122917.0,14768.0,43.678743,-79.440532
19552,515 - 69 Lynn Williams St,575000.0,1.0,1.0,0.0,Condo Apt,749.5,Apartment,Undergrnd,81702.0,6801.0,43.639029,-79.415923
19553,808 - 1600 Keele St,430000.0,1.0,1.0,1.0,Condo Apt,549.5,Apartment,Undergrnd,57144.0,17602.0,43.679358,-79.470675
19554,1811 - 195 Redpath Ave,580000.0,1.0,2.0,0.0,Condo Apt,549.5,Apartment,None,85636.0,23133.0,43.707888,-79.392802
19556,2316 - 30 Shore Breeze Dr,900000.0,2.0,2.0,1.0,Condo Apt,849.5,Apartment,Undergrnd,117457.0,4322.0,43.623764,-79.479165

In [23]:
df_copy = df_copy.drop(['Address'], axis=1)

In [24]:
df_copy

,Price,Bedrooms,Bathrooms,Parkings,Type,Estimated Size/ft,Levels,Garage,Average household income,Total population,lat,lng
0,1540180.0,2.0,2.0,1.0,Condo Apt,1299.5,Apartment,Undergrnd,122917.0,14768.0,43.680467,-79.430436
1,896000.0,2.0,2.0,1.0,Condo Apt,949.5,Apartment,Undergrnd,62171.0,4089.0,43.769796,-79.369430
2,705600.0,1.0,1.0,1.0,Condo Apt,749.5,Apartment,Undergrnd,76677.0,37644.0,43.657599,-79.383640
3,801000.0,2.0,1.0,1.0,Condo Apt,849.5,Apartment,Attached,168492.0,5488.0,43.640357,-79.542820
4,2355000.0,3.0,4.0,3.0,Detached,N/A,2-Storey,None,187227.0,6526.0,43.724902,-79.418350
...,...,...,...,...,...,...,...,...,...,...,...,...
19551,1300000.0,2.0,2.0,1.0,Condo Apt,1299.5,Apartment,Undergrnd,122917.0,14768.0,43.678743,-79.440532
19552,575000.0,1.0,1.0,0.0,Condo Apt,749.5,Apartment,Undergrnd,81702.0,6801.0,43.639029,-79.415923
19553,430000.0,1.0,1.0,1.0,Condo Apt,549.5,Apartment,Undergrnd,57144.0,17602.0,43.679358,-79.470675
19554,580000.0,1.0,2.0,0.0,Condo Apt,549.5,Apartment,None,85636.0,23133.0,43.707888,-79.392802
19556,900000.0,2.0,2.0,1.0,Condo Apt,849.5,Apartment,Undergrnd,117457.0,4322.0,43.623764,-79.479165

In [25]:
df_copy.to_csv('edited housing data.csv', index=False)

# Continuation
The project is continued and finished in the "Toronto house price predictor" file